# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # hhvm
  #- hhvm

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
before_script:
  #  - echo "extension = gmp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - phpunit --configuration phpunit.travis.xml --coverage-clover build/logs/clover.xml

after_success:
    - php vendor/bin/coveralls -v

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"