# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7
  # hhvm
  #- hhvm

before_script:
  - composer install --no-interaction
  - mkdir -p build/logs
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/phpunit/phpunit/phpunit --configuration ./phpunit.travis.xml test

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"